{
  "hash": "ea255f93236d5b2d779711145b8bc519",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab: Logistic Regression\"\nsubtitle: \"Princeton University\"\nauthor: \"Bella Fascendini\"\noutput: \n  tufte::tufte_html:\n    css: \n    tufte_variant: \"envisioned\"\n    highlight: github-dark\n    fig_height: 10\n    fig_width: 16\n    toc: true\n    toc_depth: 1\nexecute: \n  message: false\n  warning: false\nformat: \n  html:\n    code-fold: true\n    code-overflow: wrap\nengine: knitr\n---\n\n\n\n-   Assignment requirements:\n\n    -   If you are using Github (recommended), make sure to commit and push your work to GitHub regularly, at least after each exercise. Write short and informative commit messages, and share the link to your assignment with me. If not, you can also send me the **rmd** & **rendered file** via Canvas.\n\n    -   In this assignment, you will not need to code from scratch. Rather, you'll need to fill in code where needed. This assignment has a logisitic regression implementation for a scenario from EDA down to model comparison (and would be useful for whenever you may encounter such a situation in the future).\n\n    -   I want the assignments to begin reflecting a bit more of how you'd be doing things on your own, where you have some prior knowledge and you figure other things out (by referring to documentation, etc.) . In addition to the rmd, I also want you to submit to me **notes** of anything new that you learn while finishing the assignment. And any pain-points, and we'll discuss more.\n\n-   Note:\n\n    -   If you are fitting a model, display the model output in a neatly formatted table. (The `gt` `tidy` and `kable` functions can help!). `Modelsummary` also looks good(https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html)\n\n    -   Make sure that your plots are clearly labeled – for all axes, titles, etc.\\\n\n## Data: General Social Survey\n\nThe General Social Survey (GSS) has been used to measure trends in attitudes and behaviors in American society since 1972. In addition to collecting demographic information, the survey includes questions used to gauge attitudes about government spending priorities, confidence in institutions, lifestyle, and many other topics. A full description of the survey may be found here.\n\nThe data for this lab are from the 2016 General Social Survey. The original data set contains 2867 observations and 935 variables. We will use and abbreviated data set that includes the following variables:\n\nnatmass: Respondent’s answer to the following prompt:\n\n“We are faced with many problems in this country, none of which can be solved easily or inexpensively. I’m going to name some of these problems, and for each one I’d like you to tell me whether you think we’re spending too much money on it, too little money, or about the right amount…are we spending too much, too little, or about the right amount on mass transportation?”\n\nage: Age in years.\n\nsex: Sex recorded as male or female\n\nsei10: Socioeconomic index from 0 to 100\n\nregion: Region where interview took place\n\npolviews: Respondent’s answer to the following prompt:\n\n“We hear a lot of talk these days about liberals and conservatives. I’m going to show you a seven-point scale on which the political views that people might hold are arranged from extremely liberal - point 1 - to extremely conservative - point 7. Where would you place yourself on this scale?”\n\nThe data are in gss2016.csv in the data folder.\n\n## EDA\n\n> Let’s begin by making a binary variable for respondents’ views on spending on mass transportation. Create a new variable that is equal to “1” if a respondent said spending on mass transportation is about right and “0” otherwise. Then plot the proportion of the response variable, using informative labels for each category.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(readr)\nlibrary(modelsummary)\nlibrary(tidyr)\nlibrary(knitr)\nlibrary(easystats)\nlibrary(broom)\nlibrary(emmeans)\nlibrary(marginaleffects)\nlibrary(performance)\nlibrary(arm)\nlibrary(modelsummary)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data\ndata <- read.csv(\"gss2016.csv\")\n```\n:::\n\n\n\nFill in the \"\\_\\_\\_\\_\" below to encode the binary variable\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data %>%\n   mutate(mass_trans_spend_right = ifelse(natmass == \"About right\", 1, 0))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Get proportions\nmass_spend_summary <- data %>%\n  count(mass_trans_spend_right) %>%\n  mutate(proportion = n / sum(n))\n\n\n#Look at the dataframe structure. And make sure it's in a format that you can use for plotting.\n#Change structure if neederd\nmass_spend_long <- mass_spend_summary %>%\n  mutate(spend_category = ifelse(mass_trans_spend_right == 1, \"About right\", \"Not right\"))\n\n#Factorise for plot\nmass_spend_long$mass_trans_spend_right <- as.factor(mass_spend_long$mass_trans_spend_right)\n\n#Make plot\n#Hint: geom_bar lets you make stacked bar charts\n\nggplot(mass_spend_summary, aes(x = factor(mass_trans_spend_right), y = proportion, fill = factor(mass_trans_spend_right))) +\n  geom_bar(stat = \"identity\") +\n  scale_fill_manual(values = c(\"#E69F00\", \"#56B4E9\"),\n                   labels = c(\"Not right\", \"About right\")) +\n  labs(title = \"Proportion of Responses on Mass Transportation Spending\",\n       x = \"Response\",\n       y = \"Proportion\",\n       fill = \"Spending View\") +\n  scale_x_discrete(labels = c(\"Not right\", \"About right\")) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n> Recode `polviews` so it is a factor with levels that are in an order that is consistent with question on the survey. Note how the categories are spelled in the data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data %>%\n  mutate(polviews = factor(polviews,\n                          levels = c(\"Extremely liberal\", \"Liberal\", \"Slightly liberal\", \n                                   \"Moderate\", \"Slghtly conservative\", \"Conservative\", \n                                   \"Extrmly conservative\"),\n                          ordered = TRUE))\n```\n:::\n\n\n\n> Make a plot of the distribution of `polviews`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Get proportions, format, and produce a plot like you did previously for mass_trans_spend_right\npalette <- c(\n  \"#772e25\", \"#c44536\", \"#ee9b00\", \"#197278\", \"#283d3b\", \n  \"#9CC5A1\", \"#6195C6\", \"#ADA7C9\", \"#4D4861\", \"grey50\",\n  \"#d4a373\", \"#8a5a44\", \"#4a6a74\", \"#5c80a8\", \"#a9c5a0\",\n  \"#7b9b8e\", \"#e1b16a\", \"#a69b7c\", \"#9d94c4\", \"#665c54\"\n)\n\npalette_condition = c(\"#ee9b00\", \"#c44536\",\"#005f73\", \"#283d3b\", \"#9CC5A1\", \"#6195C6\", \"#ADA7C9\", \"#4D4861\")\n\nplot_aes = theme_minimal() +\n  theme(legend.position = \"top\",\n        legend.text = element_text(size = 12),\n        text = element_text(size = 16, family = \"Futura Medium\"),\n        axis.text = element_text(color = \"black\"),\n        axis.ticks.y = element_blank())\n\npolviews_summary <- data %>% #proportion\n  count(polviews) %>%\n  mutate(proportion = n / sum(n))\n\nggplot(polviews_summary, aes(x = polviews, y = proportion, fill = polviews)) +\n  geom_bar(stat = \"identity\") +\n  scale_fill_manual(values = palette) + \n  labs(title = \"Distribution of Political Views\",\n       x = \"Political Views\",\n       y = \"Proportion\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1),\n        plot.title = element_text(hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\n  plot_aes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 136\n $ line                            :List of 6\n  ..$ colour       : chr \"black\"\n  ..$ linewidth    : num 0.5\n  ..$ linetype     : num 1\n  ..$ lineend      : chr \"butt\"\n  ..$ arrow        : logi FALSE\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_line\" \"element\"\n $ rect                            :List of 5\n  ..$ fill         : chr \"white\"\n  ..$ colour       : chr \"black\"\n  ..$ linewidth    : num 0.5\n  ..$ linetype     : num 1\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_rect\" \"element\"\n $ text                            :List of 11\n  ..$ family       : chr \"Futura Medium\"\n  ..$ face         : chr \"plain\"\n  ..$ colour       : chr \"black\"\n  ..$ size         : num 16\n  ..$ hjust        : num 0.5\n  ..$ vjust        : num 0.5\n  ..$ angle        : num 0\n  ..$ lineheight   : num 0.9\n  ..$ margin       : 'margin' num [1:4] 0points 0points 0points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : logi FALSE\n  ..$ inherit.blank: logi FALSE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ title                           : NULL\n $ aspect.ratio                    : NULL\n $ axis.title                      : NULL\n $ axis.title.x                    :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 1\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 2.75points 0points 0points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.title.x.top                :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 0\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 0points 2.75points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.title.x.bottom             : NULL\n $ axis.title.y                    :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 1\n  ..$ angle        : num 90\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 2.75points 0points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.title.y.left               : NULL\n $ axis.title.y.right              :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 1\n  ..$ angle        : num -90\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 0points 0points 2.75points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.text                       :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : chr \"black\"\n  ..$ size         : 'rel' num 0.8\n  ..$ hjust        : NULL\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : NULL\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi FALSE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.text.x                     :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 1\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 2.2points 0points 0points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.text.x.top                 :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : NULL\n  ..$ vjust        : num 0\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 0points 2.2points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.text.x.bottom              : NULL\n $ axis.text.y                     :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : num 1\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 2.2points 0points 0points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.text.y.left                : NULL\n $ axis.text.y.right               :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : num 0\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 0points 0points 2.2points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.text.theta                 : NULL\n $ axis.text.r                     :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : num 0.5\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : 'margin' num [1:4] 0points 2.2points 0points 2.2points\n  .. ..- attr(*, \"unit\")= int 8\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ axis.ticks                      : list()\n  ..- attr(*, \"class\")= chr [1:2] \"element_blank\" \"element\"\n $ axis.ticks.x                    : NULL\n $ axis.ticks.x.top                : NULL\n $ axis.ticks.x.bottom             : NULL\n $ axis.ticks.y                    : list()\n  ..- attr(*, \"class\")= chr [1:2] \"element_blank\" \"element\"\n $ axis.ticks.y.left               : NULL\n $ axis.ticks.y.right              : NULL\n $ axis.ticks.theta                : NULL\n $ axis.ticks.r                    : NULL\n $ axis.minor.ticks.x.top          : NULL\n $ axis.minor.ticks.x.bottom       : NULL\n $ axis.minor.ticks.y.left         : NULL\n $ axis.minor.ticks.y.right        : NULL\n $ axis.minor.ticks.theta          : NULL\n $ axis.minor.ticks.r              : NULL\n $ axis.ticks.length               : 'simpleUnit' num 2.75points\n  ..- attr(*, \"unit\")= int 8\n $ axis.ticks.length.x             : NULL\n $ axis.ticks.length.x.top         : NULL\n $ axis.ticks.length.x.bottom      : NULL\n $ axis.ticks.length.y             : NULL\n $ axis.ticks.length.y.left        : NULL\n $ axis.ticks.length.y.right       : NULL\n $ axis.ticks.length.theta         : NULL\n $ axis.ticks.length.r             : NULL\n $ axis.minor.ticks.length         : 'rel' num 0.75\n $ axis.minor.ticks.length.x       : NULL\n $ axis.minor.ticks.length.x.top   : NULL\n $ axis.minor.ticks.length.x.bottom: NULL\n $ axis.minor.ticks.length.y       : NULL\n $ axis.minor.ticks.length.y.left  : NULL\n $ axis.minor.ticks.length.y.right : NULL\n $ axis.minor.ticks.length.theta   : NULL\n $ axis.minor.ticks.length.r       : NULL\n $ axis.line                       : list()\n  ..- attr(*, \"class\")= chr [1:2] \"element_blank\" \"element\"\n $ axis.line.x                     : NULL\n $ axis.line.x.top                 : NULL\n $ axis.line.x.bottom              : NULL\n $ axis.line.y                     : NULL\n $ axis.line.y.left                : NULL\n $ axis.line.y.right               : NULL\n $ axis.line.theta                 : NULL\n $ axis.line.r                     : NULL\n $ legend.background               : list()\n  ..- attr(*, \"class\")= chr [1:2] \"element_blank\" \"element\"\n $ legend.margin                   : 'margin' num [1:4] 5.5points 5.5points 5.5points 5.5points\n  ..- attr(*, \"unit\")= int 8\n $ legend.spacing                  : 'simpleUnit' num 11points\n  ..- attr(*, \"unit\")= int 8\n $ legend.spacing.x                : NULL\n $ legend.spacing.y                : NULL\n $ legend.key                      : list()\n  ..- attr(*, \"class\")= chr [1:2] \"element_blank\" \"element\"\n $ legend.key.size                 : 'simpleUnit' num 1.2lines\n  ..- attr(*, \"unit\")= int 3\n $ legend.key.height               : NULL\n $ legend.key.width                : NULL\n $ legend.key.spacing              : 'simpleUnit' num 5.5points\n  ..- attr(*, \"unit\")= int 8\n $ legend.key.spacing.x            : NULL\n $ legend.key.spacing.y            : NULL\n $ legend.frame                    : NULL\n $ legend.ticks                    : NULL\n $ legend.ticks.length             : 'rel' num 0.2\n $ legend.axis.line                : NULL\n $ legend.text                     :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : num 12\n  ..$ hjust        : NULL\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : NULL\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi FALSE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ legend.text.position            : NULL\n $ legend.title                    :List of 11\n  ..$ family       : NULL\n  ..$ face         : NULL\n  ..$ colour       : NULL\n  ..$ size         : NULL\n  ..$ hjust        : num 0\n  ..$ vjust        : NULL\n  ..$ angle        : NULL\n  ..$ lineheight   : NULL\n  ..$ margin       : NULL\n  ..$ debug        : NULL\n  ..$ inherit.blank: logi TRUE\n  ..- attr(*, \"class\")= chr [1:2] \"element_text\" \"element\"\n $ legend.title.position           : NULL\n $ legend.position                 : chr \"top\"\n $ legend.position.inside          : NULL\n $ legend.direction                : NULL\n $ legend.byrow                    : NULL\n $ legend.justification            : chr \"center\"\n $ legend.justification.top        : NULL\n $ legend.justification.bottom     : NULL\n $ legend.justification.left       : NULL\n $ legend.justification.right      : NULL\n $ legend.justification.inside     : NULL\n $ legend.location                 : NULL\n $ legend.box                      : NULL\n $ legend.box.just                 : NULL\n $ legend.box.margin               : 'margin' num [1:4] 0cm 0cm 0cm 0cm\n  ..- attr(*, \"unit\")= int 1\n $ legend.box.background           : list()\n  ..- attr(*, \"class\")= chr [1:2] \"element_blank\" \"element\"\n $ legend.box.spacing              : 'simpleUnit' num 11points\n  ..- attr(*, \"unit\")= int 8\n  [list output truncated]\n - attr(*, \"class\")= chr [1:2] \"theme\" \"gg\"\n - attr(*, \"complete\")= logi TRUE\n - attr(*, \"validate\")= logi TRUE\n```\n\n\n:::\n:::\n\n\n\n> Which political view occurs most frequently in this data set?\n\n# Moderate seems to occur most frequently in the data.\n\n> Make a plot displaying the relationship between satisfaction with mass transportation spending and political views. Use the plot to describe the relationship the two variables.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrelationship_plot <- data %>%\n  group_by(polviews) %>%\n  summarize(prop_satisfied = mean(mass_trans_spend_right, na.rm = TRUE)) %>%\n  \n  ggplot(aes(x = polviews, y = prop_satisfied, fill = polviews)) +\n  geom_bar(stat = \"identity\") +\n  scale_fill_manual(values = palette_condition) +\n  labs(title = \"Satisfaction with Mass Transportation Spending by Political Views\",\n       x = \"Political Views\",\n       y = \"Proportion Satisfied\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\nrelationship_plot\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\nThe more conservative one's political views are the more they think the amount of spending on mass transportation is correct.\n\n-   We’d like to use age as a quantitative variable in your model; however, it is currently a character data type because some observations are coded as \"89 or older\".\n\n> Recode age so that is a numeric variable. Note: Before making the variable numeric, you will need to replace the values \"89 or older\" with a single value.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data %>%\n  mutate(age = ifelse(age == \"89 or older\", \"89\", age),\n         age = as.numeric(age))\n```\n:::\n\n\n\n> Plot the frequency distribution of age.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data, aes(x = age)) +\n  geom_density(fill = palette[3], alpha = 0.7) +\n  labs(title = \"Distribution of Age\",\n       x = \"Age\",\n       y = \"Density\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n## Logistic regression\n\n> Let’s start by fitting a logistic regression model with just the intercept\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nintercept_only_model <- glm(\n  mass_trans_spend_right ~ 1,\n  family = binomial(link = \"logit\"),\n  data = data\n)\nsummary(intercept_only_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = mass_trans_spend_right ~ 1, family = binomial(link = \"logit\"), \n    data = data)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)   \n(Intercept)  0.11906    0.03937   3.024  0.00249 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 3581.3  on 2589  degrees of freedom\nResidual deviance: 3581.3  on 2589  degrees of freedom\nAIC: 3583.3\n\nNumber of Fisher Scoring iterations: 3\n```\n\n\n:::\n:::\n\n\n\n> Interpret the intercept in the context of the data. You can do this by converting the $\\beta_0$ parameter out of the log-odds metric to the probability metric. Make sure to include the 95% confidence intervals. Then interpret the results in a sentence or two--what is the basic thing this probability tells us about?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb0 <- coef(intercept_only_model)[1] # get coef\n\nb0_transformed <- exp(b0) / (1 + exp(b0)) # logistic transform\nprint(b0_transformed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) \n  0.5297297 \n```\n\n\n:::\n\n```{.r .cell-code}\nci_lower = b0 - 1.96 * 0.0393685\nci_upper = b0 + 1.96 * 0.0393685\n\n#transforming confidence intervals of coefficients into probabilities\np_lower = exp(ci_lower) / (1 + exp(ci_lower))\np_upper = exp(ci_upper) / (1 + exp(ci_upper))\nprint(paste(\"95% CI: [\", round(p_lower, 3), \",\", round(p_upper, 3), \"]\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"95% CI: [ 0.51 , 0.549 ]\"\n```\n\n\n:::\n:::\n\n\n\nInterpretation: The intercept-only model predicts that approximately 53% of respondents (95% CI: [51%, 55%]) think mass transportation spending is \"about right\". This represents the overall proportion of people satisfied with current mass transportation spending levels, without accounting for other factors such as demographic or political views.\n\n> Now let's fit a model using the demographic factors - `age`,`sex`, `sei10` - to predict the odds a person is satisfied with spending on mass transportation. Make any necessary adjustments to the variables so the intercept will have a meaningful interpretation. *Neatly display the model coefficients (do not display the summary output)*\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#make sure that sex is a factor (i.e. to make sure R knows it's binary/categorical, and not continuous)\ndata$sex <- as.factor(data$sex)\n\n#fit with glm()\nm1 <- glm(\n  mass_trans_spend_right ~ sex + age + sei10,\n  family = binomial(link = \"logit\"),\n  data = data\n)\nm1 %>%  #produce tidy output of model coefficients\n  tidy() %>%  \n  kable()    \n```\n\n::: {.cell-output-display}\n\n\n|term        |   estimate| std.error| statistic|   p.value|\n|:-----------|----------:|---------:|---------:|---------:|\n|(Intercept) |  0.8254509| 0.1395587|  5.914722| 0.0000000|\n|sexMale     | -0.2557439| 0.0798020| -3.204732| 0.0013519|\n|age         | -0.0061659| 0.0022824| -2.701502| 0.0069027|\n|sei10       | -0.0062271| 0.0016609| -3.749229| 0.0001774|\n\n\n:::\n:::\n\n\n\n> Consider the relationship between sex and one’s opinion about spending on mass transportation. Interpret the coefficient of sex in terms of the logs odds and OR of being satisfied with spending on mass transportation. What are the predicted probabilities for males and females on support for spending on mass transportation? Please include the 95% CIs around each estimate.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 %>% \n  tidy() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term        |   estimate| std.error| statistic|   p.value|\n|:-----------|----------:|---------:|---------:|---------:|\n|(Intercept) |  0.8254509| 0.1395587|  5.914722| 0.0000000|\n|sexMale     | -0.2557439| 0.0798020| -3.204732| 0.0013519|\n|age         | -0.0061659| 0.0022824| -2.701502| 0.0069027|\n|sei10       | -0.0062271| 0.0016609| -3.749229| 0.0001774|\n\n\n:::\n\n```{.r .cell-code}\nm1 %>% \n  tidy(exponentiate = TRUE) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term        |  estimate| std.error| statistic|   p.value|\n|:-----------|---------:|---------:|---------:|---------:|\n|(Intercept) | 2.2829100| 0.1395587|  5.914722| 0.0000000|\n|sexMale     | 0.7743403| 0.0798020| -3.204732| 0.0013519|\n|age         | 0.9938530| 0.0022824| -2.701502| 0.0069027|\n|sei10       | 0.9937922| 0.0016609| -3.749229| 0.0001774|\n\n\n:::\n\n```{.r .cell-code}\nbsex <- coef(m1)[\"sexMale\"]\n\nci_lower_lo = bsex - 1.96 * 0.0798020\nci_upper_lo = bsex + 1.96 * 0.0798020\n\nci_lower_or = 1.29 - 1.96 * 0.0798020\nci_upper_or = 1.29 + 1.96 * 0.0798020\n\nlist(\n  \"CI for log-odds\" = c(ci_lower_lo, ci_upper_lo),\n  \"CI for Odds Ratio\" = c(ci_lower_or, ci_upper_or)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`CI for log-odds`\n    sexMale     sexMale \n-0.41215578 -0.09933194 \n\n$`CI for Odds Ratio`\n[1] 1.133588 1.446412\n```\n\n\n:::\n\n```{.r .cell-code}\nemm_sex <- emmeans(m1, \"sex\", type = \"response\")\n```\n:::\n\n\n\nIf you did this right, you'll find that being female (as compared to male) is associated with an increase in the log-odds of being satisfied with spending on mass transportation by 0.2557439 units (95% CI \\[0.09, 0.41\\]), holding all other variables constant. This equates to the odds of thinking the spending amount is right in females being 1.29 times the odds of thinking this in men (95% CI \\[1.13, 1.44\\]).\n\nThe predicted probability for females to be satisfied with spending on mass transportation is 55.9% (95% CI \\[53.3%, 58.5%\\]) and that of males is 49.5% (95% CI \\[46.7%, 52.4%\\]).\\\n\\\nVerify this.\n\n> Next, consider the relationship between age and one’s opinion about spending on mass transportation. Interpret the coefficient of age in terms of the logs odds and OR of being satisfied with spending on mass transportation. Please include the 95% CIs around each estimate.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbage <- coef(m1)[\"age\"]\nse_age <- sqrt(vcov(m1)[\"age\", \"age\"])\nprint(bage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        age \n-0.00616594 \n```\n\n\n:::\n\n```{.r .cell-code}\nprint(se_age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.002282412\n```\n\n\n:::\n\n```{.r .cell-code}\nci_lower_lo = bage - 1.96 * se_age\nci_upper_lo = bage + 1.96 * se_age\n\nor_age <- exp(bage)\nci_lower_or = exp(ci_lower_lo)\nci_upper_or = exp(ci_upper_lo)\nprint(or_age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     age \n0.993853 \n```\n\n\n:::\n\n```{.r .cell-code}\nlist(\n  \"CI for log-odds\" = c(ci_lower_lo, ci_upper_lo),\n  \"CI for Odds Ratio\" = c(ci_lower_or, ci_upper_or)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`CI for log-odds`\n         age          age \n-0.010639467 -0.001692412 \n\n$`CI for Odds Ratio`\n      age       age \n0.9894169 0.9983090 \n```\n\n\n:::\n:::\n\n\n\nA one unit increase in age is associated with a decrease in the log-odds of being satisfied with spending on mass transportation by **-0.0062**, holding all other variables constant. The odds ratio is **0.994**, which confirms the **negative** relationship implied by the log-odds coefficient. Specifically, for each additional unit of age, the odds of being satisfied with mass transportation spending decrease by a factor of about **0.994**, or approximately **0.6%** per unit increase in age, holding other factors constant.\n\n> Consider the relationship between SES and one’s opinion about spending on mass transportation. Interpret the coefficient of SES in terms of the logs odds and OR of being satisfied with spending on mass transportation. Please include the 95% CIs around each estimate. ß\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbses <- coef(m1)\nbses <- coef(m1)[\"sei10\"]\n\n\nbses <- coef(m1)[\"sei10\"]\nses_se <- sqrt(vcov(m1)[\"sei10\", \"sei10\"])\n\nci_lower_log_odds <- bses - 1.96 * ses_se\nci_upper_log_odds <- bses + 1.96 * ses_se\n\nodds_ratio <- exp(bses)\nci_lower_odds_ratio <- exp(ci_lower_log_odds)\nci_upper_odds_ratio <- exp(ci_upper_log_odds)\n\nresults <- data.frame(\n  Metric = c(\"Log-odds coefficient\", \n             \"95% CI for log-odds\", \n             \"Odds Ratio\", \n             \"95% CI for Odds Ratio\"),\n  Value = c(\n    format(round(bses, 4), nsmall = 4),\n    paste0(\"[\", format(round(ci_lower_log_odds, 4), nsmall = 4), \", \", \n           format(round(ci_upper_log_odds, 4), nsmall = 4), \"]\"),\n    format(round(odds_ratio, 4), nsmall = 4),\n    paste0(\"[\", format(round(ci_lower_odds_ratio, 4), nsmall = 4), \", \", \n           format(round(ci_upper_odds_ratio, 4), nsmall = 4), \"]\")\n  )\n)\n\n# Display using kable\nkable(results)\n```\n\n::: {.cell-output-display}\n\n\n|Metric                |Value              |\n|:---------------------|:------------------|\n|Log-odds coefficient  |-0.0062            |\n|95% CI for log-odds   |[-0.0095, -0.0030] |\n|Odds Ratio            |0.9938             |\n|95% CI for Odds Ratio |[0.9906, 0.9970]   |\n\n\n:::\n:::\n\n\n\nA one unit increase in SES index is associated with a decrease in the log-odds of being satisfied with spending on mass transportation by 0.0062 units (95% CI \\[-0.0107, -0.0017\\]), holding all other variables constant. The odds ratio is less than 1 (0.9937922), which confirms the negative relationship implied by the log-odds coefficient. Specifically, for each additional unit of SES index, the odds of being satisfied with mass transportation spending decrease by a factor of about 0.993, or approximately 0.7% per unit increase in SES index, holding other factors constant (95% CI \\[0.989, 0.998\\]).\n\n## Marginal effects\n\n-   Let's examine the results on the probability scale.\n\n> Calculate the marginal effects of sex, age, and SES on mass transportation spending. You can use the `margins` package function `margins` discussed in your textbook or you can use the `marginaleffects` package `avg_slope` `avg_comparisons` discussed in lecture. Interpret each estimate.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_comparisons(m1, comparison = \"difference\") %>% \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term  |contrast      |   estimate| std.error| statistic|   p.value|   s.value|   conf.low|  conf.high|\n|:-----|:-------------|----------:|---------:|---------:|---------:|---------:|----------:|----------:|\n|age   |+1            | -0.0015153| 0.0005579| -2.716128| 0.0066050|  7.242218| -0.0026088| -0.0004219|\n|sei10 |+1            | -0.0015304| 0.0004039| -3.789362| 0.0001510| 12.692832| -0.0023219| -0.0007388|\n|sex   |Male - Female | -0.0630688| 0.0196461| -3.210251| 0.0013262|  9.558494| -0.1015743| -0.0245632|\n\n\n:::\n:::\n\n\n\n-   The marginal effect of age is **-0.00152** (95% CI \\[**0.00261, -0.00042**]). So, for each additional unit increase of age, the probability of being satisfied with mass transportation spending decreases by approximately **0.15** percentage points, holding other factors constant (p = **0.007**).\n\n-   The marginal effect of SES is **-0.00153** (95% CI \\[**0.00232, -0.00074**]). For each one-unit increase in the socioeconomic index, the probability of being satisfied with mass transportation spending decreases by approximately **0.15** percentage points, holding other variables constant.\n\n-   The marginal effect for being female compared to male is **0.06** (95% CI \\[**0.025, 0.102**]). This indicates that females are, on average, about **6.31** percentage points more likely than males to be satisfied with mass transportation spending, holding other factors constant.\n\n## Model comparison\n\n-   Now let’s see whether a person’s political views has a significant impact on their odds of being satisfied with spending on mass transportation, after accounting for the demographic factors.\n\n> Conduct a drop-in-deviance/likelihood ratio test to determine if polviews is a significant predictor of attitude towards spending on mass transportation. Name these two models `fit2` and `fit3`, respectively. Compare the two models.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit2 <- glm(\n  mass_trans_spend_right ~ sex + age + sei10,\n  family = binomial(link = \"logit\"),\n  data = data\n)\n\nfit3 <- glm(\n  mass_trans_spend_right ~ sex + age + sei10 + polviews,\n  family = binomial(link = \"logit\"),\n  data = data\n)\n\ntest_likelihoodratio(fit2, fit3) %>% \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|     |Name |Model | df| df_diff|     Chi2|  p|\n|:----|:----|:-----|--:|-------:|--------:|--:|\n|fit2 |fit2 |glm   |  4|      NA|       NA| NA|\n|fit3 |fit3 |glm   | 10|       6| 63.02844|  0|\n\n\n:::\n:::\n\n\n\n> Is the model with polviews better than the model without?\n\n-   Yes.\n\n## Visualization\n\n-   Let’s plot the results\n\n-   We next use the model to produce visualizations:\n\n    -   Given the code below, interpet what is being plotted:\n\n        -   pol_plot : This plot shows the predicted probability of being satisfied with mass transportation spending across different                            political views. It shows that as political ideology becomes more conservative, the probability of being                                   satisfied increases.\n\n        -   sex_plot : This plot shows the predicted probability of satisfaction with mass transportation spending for males and females.                         It highlights that females are more likely than males to consider the current spending level as \"about right.\"\n\n        -   ses_plot: This plot shows the effect of SES on the predicted probability of satisfaction with mass transportation                                    spending. It suggests that as SES increases, satisfaction decreases. The shaded region represents the confidence                           interval around the prediction.\n\n    ::: callout-tip\n    -   adjust the various settings in your plot to make it look professional.\n\n    -   You can use `ggeffects` to get the predicted probabilities for these models.\n    :::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggeffects)\n\n\ncolors <- c(\"Extremely liberal\" = \"black\",\n            \"Liberal\" = \"#0e2f44\",  # Dark blue\n            \"Slightly liberal\" = \"#1d5a6c\",  # Less dark blue\n            \"Moderate\" = \"#358ca3\",  # Medium blue\n            \"Slghtly conservative\" = \"#71b9d1\",  # Light blue\n            \"Conservative\" = \"#a6dcef\",  # Lighter blue\n            \"Extrmly conservative\" = \"#d0f0fd\")  # Very light blue\n\npp_pol <- ggemmeans(fit3, terms = c(\"polviews\"))\n\n# Adjusted plot with gradient colors\npol_plot <- ggplot(pp_pol, aes(x = x, y = predicted, color = x)) +\n  geom_point(size = 2) +\n  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +\n  scale_color_manual(values = colors) +\n  labs(title = \"Effect of Political Views on Satisfaction with Mass Transportation\",\n       x = \"Political Views\", y = \"Predicted Probability\",\n       color = \"Political Views\") +\n  theme_minimal()\n\npol_plot\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-1.png){width=1152}\n:::\n\n```{.r .cell-code}\npp_sex <- ggemmeans(fit3, terms = c(\"sex\"))\n\nsex_plot <- ggplot(pp_sex, aes(x = x, y = predicted, color = x)) +\n  geom_point(size = 2) +\n  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +\n  labs(title = \"Effect of Sex on Satisfaction with Mass Transportation\",\n       x = \"Sex\", y = \"Predicted Probability\",\n       color = \"Sex\") +\n  theme_minimal()\n\npp_sex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Predicted probabilities of mass_trans_spend_right\n\nsex    | Predicted |     95% CI\n-------------------------------\nFemale |      0.55 | 0.51, 0.58\nMale   |      0.48 | 0.44, 0.51\n\nAdjusted for:\n*   age = 48.90\n* sei10 = 46.07\n```\n\n\n:::\n\n```{.r .cell-code}\npp_ses <- ggemmeans(fit3, terms = \"sei10\")\n\n\nses_plot <-  ggplot(pp_ses, aes(x = x, y = predicted)) +\n  geom_line(color = \"#2c7fb8\", size = 1) + \n  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), fill = \"#2c7fb8\", alpha = 0.2) +  # Add a confidence interval band\n  labs(title = \"Effect of SES on Satisfaction with Mass Transportation\",\n       x = \"Socioeconomic Status\", y = \"Predicted Probability\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")  \nses_plot\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-2.png){width=1152}\n:::\n:::\n\n\n\n## Model Assumptions\n\n-   Is the logistic model a good choice for this data?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinned_residuals(fit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: About 86% of the residuals are inside the error bounds (~95% or higher would be good).\n```\n\n\n:::\n:::\n\n\n\n::: callout-note\nAnswer: The plots do not reveal any major systematic deviations from randomness. This suggests that the logistic regression model is a good choice for these data.\n:::\n\n## Model fit\n\n-   Calculate the $R^2$ for this model\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr2_mcfadden(fit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Generalized Linear Regression\n       R2: 0.010\n  adj. R2: 0.009\n```\n\n\n:::\n:::\n\n\n\n> R2 interpretation: The R^2 value suggests that while the predictors have a statistically significant effect, a substantial portion of the variability in satisfaction remains unexplained.\n>\n> Next, Take a look at the binned residual plots for each continuous predictor variable and look at linearity. Is there a predictor that sticks out? What can we do to improve model fit in this case?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinned_residuals(fit2, term=\"sei10\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: About 88% of the residuals are inside the error bounds (~95% or higher would be good).\n```\n\n\n:::\n\n```{.r .cell-code}\nbinned_residuals(fit2, term=\"age\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOk: About 98% of the residuals are inside the error bounds.\n```\n\n\n:::\n\n```{.r .cell-code}\nbinned_residuals(fit2, term=\"sei10\") %>% plot(show_dots=TRUE)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n\n```{.r .cell-code}\nbinned_residuals(fit2, term=\"age\") %>% plot(show_dots=TRUE)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-21-2.png){width=672}\n:::\n:::\n\n\n\n::: callout-note\n-   ::: callout-note\n    The binned residual plot for sei10 curves slightly, suggesting that SES may not have a simple linear relationship with satisfaction. The plot for age looks more linear. To improve the model, we could try adding a squared term for SES.\n    :::\n:::\n\n## Testing Polviews\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(fit3, \"polviews\") %>% pairs() %>% as.data.frame() %>% filter(p.value < .05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                                   estimate        SE  df z.ratio\n Extremely liberal - Moderate             -0.9266262 0.1950664 Inf  -4.750\n Extremely liberal - Slghtly conservative -0.8487137 0.2127293 Inf  -3.990\n Extremely liberal - Conservative         -0.9935486 0.2108369 Inf  -4.712\n Extremely liberal - Extrmly conservative -1.3402621 0.2792876 Inf  -4.799\n Liberal - Moderate                       -0.7090022 0.1308520 Inf  -5.418\n Liberal - Slghtly conservative           -0.6310897 0.1555805 Inf  -4.056\n Liberal - Conservative                   -0.7759246 0.1532081 Inf  -5.065\n Liberal - Extrmly conservative           -1.1226380 0.2392048 Inf  -4.693\n Slightly liberal - Extrmly conservative  -0.7334002 0.2412625 Inf  -3.040\n p.value\n  <.0001\n  0.0013\n  0.0001\n  <.0001\n  <.0001\n  0.0010\n  <.0001\n  0.0001\n  0.0382\n\nResults are averaged over the levels of: sex \nResults are given on the log odds ratio (not the response) scale. \nP value adjustment: tukey method for comparing a family of 7 estimates \n```\n\n\n:::\n\n```{.r .cell-code}\nemmeans(fit3, \"polviews\", type=\"response\") %>% pairs() %>% as.data.frame() %>% filter(p.value < .05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                                 odds.ratio         SE  df null\n Extremely liberal / Moderate              0.3958871 0.07722426 Inf    1\n Extremely liberal / Slghtly conservative  0.4279651 0.09104070 Inf    1\n Extremely liberal / Conservative          0.3702605 0.07806458 Inf    1\n Extremely liberal / Extrmly conservative  0.2617771 0.07311109 Inf    1\n Liberal / Moderate                        0.4921350 0.06439684 Inf    1\n Liberal / Slghtly conservative            0.5320118 0.08277063 Inf    1\n Liberal / Conservative                    0.4602780 0.07051835 Inf    1\n Liberal / Extrmly conservative            0.3254202 0.07784206 Inf    1\n Slightly liberal / Extrmly conservative   0.4802732 0.11587191 Inf    1\n z.ratio p.value\n  -4.750  <.0001\n  -3.990  0.0013\n  -4.712  0.0001\n  -4.799  <.0001\n  -5.418  <.0001\n  -4.056  0.0010\n  -5.065  <.0001\n  -4.693  0.0001\n  -3.040  0.0382\n\nResults are averaged over the levels of: sex \nP value adjustment: tukey method for comparing a family of 7 estimates \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n:::\n\n\n\n-   Conservatives are **2.7** times more likely to support mass transit spending compared to extremely liberal and liberal\n\n-   Extreme liberals are **2.5** times more likely to support spending compared to conservatives, moderates and slight conservatives\n\n-   Extrm conservatives are **3.1** times more likely to support mass spending than liberals and slight liberals\n\n-   Liberals are **2.0** times more likely to support spending than moderates and slight conservatives.\n\n## Conclusion\n\nBased on the model summary below, and the three figures, we can conclude that both demographic factors and political views significantly influence satisfaction with mass transportation spending. Specifically, women are more likely to support current spending than men, older individuals are less likely to support current spending, and individuals with higher SES are less likely to support current spending. Political views also play a significant role, with conservatives more likely to support current spending than liberal individuals.\n\nThe logistic regression model fits the data reasonably well, but the residual analysis suggests SES might have a non-linear relationship with satisfaction. The R^2 value indicates that while the model explains some variability, additional factors may be at play. Future research could explore more complex relationships between SES and satisfaction to improve model fit.\n\n\n\n\n\n|         | Df| Deviance| Resid. Df| Resid. Dev|  Pr(>Chi)|\n|:--------|--:|--------:|---------:|----------:|---------:|\n|NULL     | NA|       NA|      2589|   3581.340|        NA|\n|sex      |  1| 11.31903|      2588|   3570.021| 0.0007672|\n|age      |  1| 10.10603|      2587|   3559.915| 0.0014778|\n|sei10    |  1| 14.11908|      2586|   3545.796| 0.0001716|\n|polviews |  6| 63.02844|      2580|   3482.768| 0.0000000|\n\n\n\nTable 1\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 1: Effect of Sex on Satisfaction with Mass Transportation](index_files/figure-html/plot-sexviews-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 2: Effect of SES  on Satisfaction with Mass Transportation](index_files/figure-html/plot-sesviews-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 3: Effect of Political Views on Satisfaction with Mass Transportation](index_files/figure-html/plot-polviews-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}